server {
    listen 80;
    server_name _;

    # DigiFacto TV
    location /DigiFacto_TV/ {
        root /usr/share/nginx/html;
        index index.html;
        # This ensures Angular routing works (prevents 404 on refresh)
        try_files $uri $uri/ /DigiFacto_TV/index.html;
    }

    # Redirect root (/) to DigiFacto TV
    location = / {
        return 301 /DigiFacto_TV/;
    }
}
